### ISSUE TITLE
import pkg from '@feathersjs/errors'; const { BadRequest } = pkg;

### ISSUE THREAD

**Issue by joacub** [feathersjs-ecosystem/feathers-hooks-common#671] opened 2022-06-03 19:02 UTC
Error in import when main project is type: module

import pkg from '@feathersjs/errors';
const { BadRequest } = pkg;

feathers-hooks-version 6.11.1

**Comment by fratzinger** [comment] 2022-06-04 11:10
duplicate of #673

**Closed by fratzinger** 2022-06-04 11:10 UTC
