### ISSUE TITLE
Modules import

### ISSUE THREAD

**Issue by joacub** [feathersjs-ecosystem/feathers-hooks-common#672] opened 2022-06-03 19:05 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `feathers-hooks-common@6.1.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/feathers-hooks-common/dist/index.mjs b/node_modules/feathers-hooks-common/dist/index.mjs
index 7ecf617..03d1cbe 100644
--- a/node_modules/feathers-hooks-common/dist/index.mjs
+++ b/node_modules/feathers-hooks-common/dist/index.mjs
@@ -42,7 +42,9 @@ function actOn(what, ...hooks2) {
 }
 
 // src/hooks/alter-items.ts
-import { BadRequest } from "@feathersjs/errors";
+import errors from "@feathersjs/errors";
+
+const { BadRequest } = errors;
 
 // src/common/pluck.ts
 import _pick from "lodash/pick";
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by fratzinger** [comment] 2022-06-04 11:10
duplicate of #673

**Closed by fratzinger** 2022-06-04 11:10 UTC
